import { chromium, devices } from '@playwright/test';
const out = process.env.OUT!;
const browser = await chromium.launch();
const ctx = await browser.newContext({ ...devices['iPhone 13'] });
const page = await ctx.newPage();
await page.clock.install({ time: new Date('2026-09-22T15:00:00-07:00') });
await page.goto('http://localhost:4173/boundless-neon/#/settings');
await page.waitForFunction(() => !!(window as any).__bneon);
await page.evaluate(async () => { const h = (window as any).__bneon; await h.updateSettings({ firstLaunchDone: true, prenatalMode: false, age: 30, silentSwitchWarned: true }); await h.startBlock('2026-09-21'); });
await page.goto('http://localhost:4173/boundless-neon/#/today');
await page.waitForSelector('[data-testid="today"]');
await page.screenshot({ path: `${out}/b1-today.png`, fullPage: false });
await page.goto('http://localhost:4173/boundless-neon/#/brief/B?day=2&slot=main&variant=seqB');
await page.waitForSelector('[data-testid="brief-page"]');
await page.locator('[data-testid="brief-exercise"]').nth(2).locator('summary').click();
await page.screenshot({ path: `${out}/b2-brief-foundation.png`, fullPage: false });
await page.mouse.wheel(0, 700);
await page.waitForTimeout(300);
await page.screenshot({ path: `${out}/b3-brief-scrolled.png`, fullPage: false });
await page.goto('http://localhost:4173/boundless-neon/#/session/C?day=2&slot=main');
await page.waitForSelector('[data-testid="timer"]');
await page.mouse.wheel(0, 900);
await page.waitForTimeout(300);
await page.screenshot({ path: `${out}/b4-setup-scrolled.png`, fullPage: false });
await page.goto('http://localhost:4173/boundless-neon/#/schedule/5');
await page.waitForSelector('[data-testid="day-preview"]');
await page.screenshot({ path: `${out}/b5-daypage.png`, fullPage: false });
await browser.close();
console.log('done');
