import { chromium, devices } from '@playwright/test';
const out = process.env.OUT!;
const browser = await chromium.launch();
const ctx = await browser.newContext({ ...devices['iPhone 13'] });
const page = await ctx.newPage();
await page.clock.install({ time: new Date('2026-09-23T15:00:00-07:00') });
await page.goto('http://localhost:4173/boundless-neon/#/today');
await page.waitForSelector('[data-testid="first-launch"]');
await page.screenshot({ path: `${out}/01-first-launch.png`, fullPage: true });
await page.getByTestId('cleared-btn').click();
await page.getByTestId('clearance-save').click();
await page.waitForSelector('[data-testid="start-date-card"]');
await page.evaluate(async () => { const h = (window as any).__bneon; await h.updateSettings({ dueDate: '2027-09-03', age: 30, providerLimits: 'Example: keep it conversational.' }); await h.startBlock('2026-09-21'); });
await page.waitForSelector('[data-testid="today"]');
await page.screenshot({ path: `${out}/02-today.png`, fullPage: true });
await page.goto('http://localhost:4173/boundless-neon/#/schedule');
await page.waitForSelector('[data-testid="day-1"]');
await page.screenshot({ path: `${out}/03-schedule.png`, fullPage: true });
await page.goto('http://localhost:4173/boundless-neon/#/moves');
await page.waitForSelector('[data-testid="library"]');
await page.screenshot({ path: `${out}/04-library.png`, fullPage: false });
await page.goto('http://localhost:4173/boundless-neon/#/session/A?day=3&slot=main&variant=kbSwings');
await page.waitForSelector('[data-testid="timer"]');
await page.screenshot({ path: `${out}/05-session-setup.png`, fullPage: true });
await page.getByTestId('start').click();
await page.clock.runFor(10_000 + 20_000 + 2_000);
await page.screenshot({ path: `${out}/06-timer-rest.png`, fullPage: false });
await page.goto('http://localhost:4173/boundless-neon/#/settings');
await page.waitForSelector('[data-testid="settings"]');
await page.screenshot({ path: `${out}/07-settings.png`, fullPage: true });
await page.goto('http://localhost:4173/boundless-neon/#/session/B?day=3&slot=main&variant=seqA');
await page.waitForSelector('[data-testid="foundation-stepper"]');
await page.screenshot({ path: `${out}/08-foundation.png`, fullPage: false });
await browser.close();
console.log('done');
