import { chromium, devices } from '@playwright/test';
const out = process.env.OUT!;
const browser = await chromium.launch();
const ctx = await browser.newContext({ ...devices['iPhone 13'] });
const page = await ctx.newPage();
await page.clock.install({ time: new Date('2026-09-22T15:00:00-07:00') });
await page.goto('http://localhost:4173/boundless-neon/#/settings');
await page.waitForFunction(() => !!(window as any).__bneon);
await page.evaluate(async () => { const h = (window as any).__bneon; await h.updateSettings({ firstLaunchDone: true, prenatalMode: true, dueDate: '2027-09-03', clearanceDate: '2026-09-01', age: 30, silentSwitchWarned: true, theme: 'light' }); await h.startBlock('2026-09-21'); });
await page.goto('http://localhost:4173/boundless-neon/#/today');
await page.waitForSelector('[data-testid="today"]');
await page.screenshot({ path: `${out}/l1-today.png` });
await page.goto('http://localhost:4173/boundless-neon/#/session/A?day=2&slot=main');
await page.waitForSelector('[data-testid="timer"]');
await page.getByTestId('start').click();
await page.clock.runFor(10_000 + 20_000 + 2_000);
await page.screenshot({ path: `${out}/l2-timer.png` });
await page.goto('http://localhost:4173/boundless-neon/#/settings');
await page.waitForSelector('[data-testid="appearance"]');
await page.getByTestId('appearance').scrollIntoViewIfNeeded();
await page.screenshot({ path: `${out}/l3-settings.png` });
await page.goto('http://localhost:4173/boundless-neon/#/schedule');
await page.waitForSelector('[data-testid="day-1"]');
await page.screenshot({ path: `${out}/l4-schedule.png` });
await browser.close();
console.log('done');
